name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          - "5.16"
          - "5.42"
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@fa3bdcb0144a50651e317f30949bb4491e74a6e4 # v1.37.0
        with:
          perl-version: ${{ matrix.perl }}
      - name: test
        run: |
          cpm install
          perl Build.PL
          ./Build
          ./Build test
